### ISSUE TITLE
Add dynamic type validation of post data

### ISSUE THREAD

**Issue by Dominic-DallOsto** [Dominic-DallOsto/zotero-api-endpoint#2]
As explained [here](https://blog.logrocket.com/dynamic-type-validation-in-typescript/) - would be nice to set this up with [AJV](https://github.com/ajv-validator/ajv) and [TypeScript JSON Validator](https://github.com/ForbesLindesay/typescript-json-validator).

**Comment by cboulanger** [comment]
Funny, I had the exact same idea!

**Comment by cboulanger** [comment]
My PR makes this easier because it separates the request-response stuff from the actual methods which take typeable input and output without worrying about marshaling the data.

I am working with https://www.postman.com/ to run tests against the endpoints. Probably we should set up a group with data fixtures to run tests against. I think Postman lets you develop these tests visually and the export a node/Chai version of it for automated testing. Could make sense if this catches on.
